/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "FreeRTOS.h"
#include "portmacro.h"
#include "task.h"

#include "stm32l4xx_hal.h"

static void prvSetupHardware( void );
static void vStartTasks( void );

static void vReadUARTTask( void * pvParameters );
static void vReadI2CTask( void * pvParameters );
static void vWriteSPITask( void * pvParameters );

int main(void)
{
    prvSetupHardware();

    vStartTasks();

    vTaskStartScheduler();

	for(;;){}
}

static void prvSetupHardware( void )
{
    HAL_Init();

    /* Ensure all priority bits are assigned as preemption priority bits. */
    // NVIC_PriorityGroupConfig( NVIC_PriorityGroup_4 );

    /* Setup the LED outputs. */
    // vParTestInitialise();

    /* Configure the button input.  This configures the interrupt to use the
     * lowest interrupt priority, so it is ok to use the ISR safe FreeRTOS API
     * from the button interrupt handler. */
    // STM_EVAL_PBInit( BUTTON_USER, BUTTON_MODE_EXTI );
}

static void vStartTasks( void )
{
    UBaseType_t uxUARTPriority = tskIDLE_PRIORITY + 1UL;
    UBaseType_t uxI2CPriority = tskIDLE_PRIORITY + 2UL;
    UBaseType_t uxSPIPriority = tskIDLE_PRIORITY + 3UL;
    const StackType_t uxStackDepth = configMINIMAL_STACK_SIZE;

    xTaskCreate( vReadUARTTask, "UARTx", uxStackDepth, NULL, uxUARTPriority, ( TaskHandle_t * ) NULL );
    xTaskCreate( vReadI2CTask, "I2Cx", uxStackDepth, NULL, uxI2CPriority, ( TaskHandle_t * ) NULL );
    xTaskCreate( vWriteSPITask, "SPIx", uxStackDepth, NULL, uxSPIPriority, ( TaskHandle_t * ) NULL );
}

static void vReadUARTTask( void * pvParameters )
{
    /* Queue a message for printing to say the task has started. */
    // vPrintDisplayMessage( &pcTaskStartMsg );

    for( ; ; )
    {
    }
}

static void vReadI2CTask( void * pvParameters )
{
    /* Queue a message for printing to say the task has started. */
    // vPrintDisplayMessage( &pcTaskStartMsg );

    for( ; ; )
    {
    }
}

static void vWriteSPITask( void * pvParameters )
{
    /* Queue a message for printing to say the task has started. */
    // vPrintDisplayMessage( &pcTaskStartMsg );

    for( ; ; )
    {
    }
}

void vApplicationIdleHook( void )
{
    /* vApplicationIdleHook() will only be called if configUSE_IDLE_HOOK is set
     * to 1 in FreeRTOSConfig.h.  It will be called on each iteration of the idle
     * task.  It is essential that code added to this hook function never attempts
     * to block in any way (for example, call xQueueReceive() with a block time
     * specified, or call vTaskDelay()).  If the application makes use of the
     * vTaskDelete() API function (as this demo application does) then it is also
     * important that vApplicationIdleHook() is permitted to return to its calling
     * function, because it is the responsibility of the idle task to clean up
     * memory allocated by the kernel to any task that has since been deleted. */
}
